// <auto-generated />
namespace RestaurantReview.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rememberhitsdne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rememberhitsdne));
        
        string IMigrationMetadata.Id
        {
            get { return "201810040439217_remember h its dne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
