// <auto-generated />
namespace RestaurantReview.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newSeed1000Records : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newSeed1000Records));
        
        string IMigrationMetadata.Id
        {
            get { return "201806120112209_new Seed 1000 Records"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
